// Code generated by MockGen. DO NOT EDIT.
// Source: meetings-editor/internal/transport/http/handler (interfaces: ExportService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_export_svc.go -package=mocks meetings-editor/internal/transport/http/handler ExportService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	meeting "meetings-editor/internal/domain/meeting"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExportService is a mock of ExportService interface.
type MockExportService struct {
	ctrl     *gomock.Controller
	recorder *MockExportServiceMockRecorder
	isgomock struct{}
}

// MockExportServiceMockRecorder is the mock recorder for MockExportService.
type MockExportServiceMockRecorder struct {
	mock *MockExportService
}

// NewMockExportService creates a new mock instance.
func NewMockExportService(ctrl *gomock.Controller) *MockExportService {
	mock := &MockExportService{ctrl: ctrl}
	mock.recorder = &MockExportServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExportService) EXPECT() *MockExportServiceMockRecorder {
	return m.recorder
}

// Agenda mocks base method.
func (m_2 *MockExportService) Agenda(m *meeting.Meeting) ([]byte, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Agenda", m)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Agenda indicates an expected call of Agenda.
func (mr *MockExportServiceMockRecorder) Agenda(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Agenda", reflect.TypeOf((*MockExportService)(nil).Agenda), m)
}

// Participants mocks base method.
func (m_2 *MockExportService) Participants(m *meeting.Meeting) ([]byte, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Participants", m)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Participants indicates an expected call of Participants.
func (mr *MockExportServiceMockRecorder) Participants(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Participants", reflect.TypeOf((*MockExportService)(nil).Participants), m)
}
