// Code generated by MockGen. DO NOT EDIT.
// Source: meetings-editor/internal/service/meeting (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_meeting_svc.go -package=mocks -mock_names Service=MockMeetingService meetings-editor/internal/service/meeting Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	meeting "meetings-editor/internal/domain/meeting"
	meeting0 "meetings-editor/internal/service/meeting"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMeetingService is a mock of Service interface.
type MockMeetingService struct {
	ctrl     *gomock.Controller
	recorder *MockMeetingServiceMockRecorder
	isgomock struct{}
}

// MockMeetingServiceMockRecorder is the mock recorder for MockMeetingService.
type MockMeetingServiceMockRecorder struct {
	mock *MockMeetingService
}

// NewMockMeetingService creates a new mock instance.
func NewMockMeetingService(ctrl *gomock.Controller) *MockMeetingService {
	mock := &MockMeetingService{ctrl: ctrl}
	mock.recorder = &MockMeetingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeetingService) EXPECT() *MockMeetingServiceMockRecorder {
	return m.recorder
}

// AddAgendaItem mocks base method.
func (m *MockMeetingService) AddAgendaItem(ctx context.Context, meetingID, text string, speakerIDs []int) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAgendaItem", ctx, meetingID, text, speakerIDs)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAgendaItem indicates an expected call of AddAgendaItem.
func (mr *MockMeetingServiceMockRecorder) AddAgendaItem(ctx, meetingID, text, speakerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgendaItem", reflect.TypeOf((*MockMeetingService)(nil).AddAgendaItem), ctx, meetingID, text, speakerIDs)
}

// AddAgendaItemSpeaker mocks base method.
func (m *MockMeetingService) AddAgendaItemSpeaker(ctx context.Context, meetingID string, itemID, speakerID int) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAgendaItemSpeaker", ctx, meetingID, itemID, speakerID)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAgendaItemSpeaker indicates an expected call of AddAgendaItemSpeaker.
func (mr *MockMeetingServiceMockRecorder) AddAgendaItemSpeaker(ctx, meetingID, itemID, speakerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgendaItemSpeaker", reflect.TypeOf((*MockMeetingService)(nil).AddAgendaItemSpeaker), ctx, meetingID, itemID, speakerID)
}

// AddPerson mocks base method.
func (m *MockMeetingService) AddPerson(ctx context.Context, meetingID string, personID int) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPerson", ctx, meetingID, personID)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPerson indicates an expected call of AddPerson.
func (mr *MockMeetingServiceMockRecorder) AddPerson(ctx, meetingID, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPerson", reflect.TypeOf((*MockMeetingService)(nil).AddPerson), ctx, meetingID, personID)
}

// Create mocks base method.
func (m *MockMeetingService) Create(ctx context.Context, req *meeting0.CreateRequest) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMeetingServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMeetingService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockMeetingService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMeetingServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMeetingService)(nil).Delete), ctx, id)
}

// DeleteAgendaItem mocks base method.
func (m *MockMeetingService) DeleteAgendaItem(ctx context.Context, meetingID string, itemID int) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgendaItem", ctx, meetingID, itemID)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAgendaItem indicates an expected call of DeleteAgendaItem.
func (mr *MockMeetingServiceMockRecorder) DeleteAgendaItem(ctx, meetingID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgendaItem", reflect.TypeOf((*MockMeetingService)(nil).DeleteAgendaItem), ctx, meetingID, itemID)
}

// GetAll mocks base method.
func (m *MockMeetingService) GetAll(ctx context.Context, limit, offset int) ([]meeting.Meeting, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, offset)
	ret0, _ := ret[0].([]meeting.Meeting)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMeetingServiceMockRecorder) GetAll(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMeetingService)(nil).GetAll), ctx, limit, offset)
}

// GetByID mocks base method.
func (m *MockMeetingService) GetByID(ctx context.Context, id string) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMeetingServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMeetingService)(nil).GetByID), ctx, id)
}

// RemoveAgendaItemSpeaker mocks base method.
func (m *MockMeetingService) RemoveAgendaItemSpeaker(ctx context.Context, meetingID string, itemID, speakerID int) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAgendaItemSpeaker", ctx, meetingID, itemID, speakerID)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveAgendaItemSpeaker indicates an expected call of RemoveAgendaItemSpeaker.
func (mr *MockMeetingServiceMockRecorder) RemoveAgendaItemSpeaker(ctx, meetingID, itemID, speakerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAgendaItemSpeaker", reflect.TypeOf((*MockMeetingService)(nil).RemoveAgendaItemSpeaker), ctx, meetingID, itemID, speakerID)
}

// RemovePerson mocks base method.
func (m *MockMeetingService) RemovePerson(ctx context.Context, meetingID string, personID int) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePerson", ctx, meetingID, personID)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemovePerson indicates an expected call of RemovePerson.
func (mr *MockMeetingServiceMockRecorder) RemovePerson(ctx, meetingID, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePerson", reflect.TypeOf((*MockMeetingService)(nil).RemovePerson), ctx, meetingID, personID)
}

// ReorderAgendaItemSpeakers mocks base method.
func (m *MockMeetingService) ReorderAgendaItemSpeakers(ctx context.Context, meetingID string, itemID int, speakerIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderAgendaItemSpeakers", ctx, meetingID, itemID, speakerIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderAgendaItemSpeakers indicates an expected call of ReorderAgendaItemSpeakers.
func (mr *MockMeetingServiceMockRecorder) ReorderAgendaItemSpeakers(ctx, meetingID, itemID, speakerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderAgendaItemSpeakers", reflect.TypeOf((*MockMeetingService)(nil).ReorderAgendaItemSpeakers), ctx, meetingID, itemID, speakerIDs)
}

// ReorderAgendaItems mocks base method.
func (m *MockMeetingService) ReorderAgendaItems(ctx context.Context, meetingID string, agendaItemIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderAgendaItems", ctx, meetingID, agendaItemIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderAgendaItems indicates an expected call of ReorderAgendaItems.
func (mr *MockMeetingServiceMockRecorder) ReorderAgendaItems(ctx, meetingID, agendaItemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderAgendaItems", reflect.TypeOf((*MockMeetingService)(nil).ReorderAgendaItems), ctx, meetingID, agendaItemIDs)
}

// ReorderPeople mocks base method.
func (m *MockMeetingService) ReorderPeople(ctx context.Context, meetingID string, personIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderPeople", ctx, meetingID, personIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderPeople indicates an expected call of ReorderPeople.
func (mr *MockMeetingServiceMockRecorder) ReorderPeople(ctx, meetingID, personIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderPeople", reflect.TypeOf((*MockMeetingService)(nil).ReorderPeople), ctx, meetingID, personIDs)
}

// SetChairperson mocks base method.
func (m *MockMeetingService) SetChairperson(ctx context.Context, meetingID string, personID int) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChairperson", ctx, meetingID, personID)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetChairperson indicates an expected call of SetChairperson.
func (mr *MockMeetingServiceMockRecorder) SetChairperson(ctx, meetingID, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChairperson", reflect.TypeOf((*MockMeetingService)(nil).SetChairperson), ctx, meetingID, personID)
}

// Update mocks base method.
func (m *MockMeetingService) Update(ctx context.Context, meetingID string, req *meeting0.UpdateRequest) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, meetingID, req)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMeetingServiceMockRecorder) Update(ctx, meetingID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMeetingService)(nil).Update), ctx, meetingID, req)
}

// UpdateAgendaItem mocks base method.
func (m *MockMeetingService) UpdateAgendaItem(ctx context.Context, meetingID string, itemID int, text string, speakerIDs []int) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgendaItem", ctx, meetingID, itemID, text, speakerIDs)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAgendaItem indicates an expected call of UpdateAgendaItem.
func (mr *MockMeetingServiceMockRecorder) UpdateAgendaItem(ctx, meetingID, itemID, text, speakerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgendaItem", reflect.TypeOf((*MockMeetingService)(nil).UpdateAgendaItem), ctx, meetingID, itemID, text, speakerIDs)
}
