// Code generated by MockGen. DO NOT EDIT.
// Source: meetings-editor/internal/domain/meeting (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_meeting_repo.go -package=mocks -mock_names Repository=MockMeetingRepository meetings-editor/internal/domain/meeting Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	meeting "meetings-editor/internal/domain/meeting"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMeetingRepository is a mock of Repository interface.
type MockMeetingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMeetingRepositoryMockRecorder
	isgomock struct{}
}

// MockMeetingRepositoryMockRecorder is the mock recorder for MockMeetingRepository.
type MockMeetingRepositoryMockRecorder struct {
	mock *MockMeetingRepository
}

// NewMockMeetingRepository creates a new mock instance.
func NewMockMeetingRepository(ctrl *gomock.Controller) *MockMeetingRepository {
	mock := &MockMeetingRepository{ctrl: ctrl}
	mock.recorder = &MockMeetingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeetingRepository) EXPECT() *MockMeetingRepositoryMockRecorder {
	return m.recorder
}

// AddAgendaItem mocks base method.
func (m *MockMeetingRepository) AddAgendaItem(ctx context.Context, meetingID, text string, speakerIDs []int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAgendaItem", ctx, meetingID, text, speakerIDs)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAgendaItem indicates an expected call of AddAgendaItem.
func (mr *MockMeetingRepositoryMockRecorder) AddAgendaItem(ctx, meetingID, text, speakerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgendaItem", reflect.TypeOf((*MockMeetingRepository)(nil).AddAgendaItem), ctx, meetingID, text, speakerIDs)
}

// AddAgendaItemSpeaker mocks base method.
func (m *MockMeetingRepository) AddAgendaItemSpeaker(ctx context.Context, meetingID string, itemID, speakerID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAgendaItemSpeaker", ctx, meetingID, itemID, speakerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAgendaItemSpeaker indicates an expected call of AddAgendaItemSpeaker.
func (mr *MockMeetingRepositoryMockRecorder) AddAgendaItemSpeaker(ctx, meetingID, itemID, speakerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgendaItemSpeaker", reflect.TypeOf((*MockMeetingRepository)(nil).AddAgendaItemSpeaker), ctx, meetingID, itemID, speakerID)
}

// AddPerson mocks base method.
func (m *MockMeetingRepository) AddPerson(ctx context.Context, meetingID string, personID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPerson", ctx, meetingID, personID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPerson indicates an expected call of AddPerson.
func (mr *MockMeetingRepositoryMockRecorder) AddPerson(ctx, meetingID, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPerson", reflect.TypeOf((*MockMeetingRepository)(nil).AddPerson), ctx, meetingID, personID)
}

// Create mocks base method.
func (m_2 *MockMeetingRepository) Create(ctx context.Context, m *meeting.Meeting) (*meeting.Meeting, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMeetingRepositoryMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMeetingRepository)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockMeetingRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMeetingRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMeetingRepository)(nil).Delete), ctx, id)
}

// DeleteAgendaItem mocks base method.
func (m *MockMeetingRepository) DeleteAgendaItem(ctx context.Context, meetingID string, itemID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgendaItem", ctx, meetingID, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAgendaItem indicates an expected call of DeleteAgendaItem.
func (mr *MockMeetingRepositoryMockRecorder) DeleteAgendaItem(ctx, meetingID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgendaItem", reflect.TypeOf((*MockMeetingRepository)(nil).DeleteAgendaItem), ctx, meetingID, itemID)
}

// GetAll mocks base method.
func (m *MockMeetingRepository) GetAll(ctx context.Context, limit, offset int) ([]meeting.Meeting, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, offset)
	ret0, _ := ret[0].([]meeting.Meeting)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMeetingRepositoryMockRecorder) GetAll(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMeetingRepository)(nil).GetAll), ctx, limit, offset)
}

// GetByID mocks base method.
func (m *MockMeetingRepository) GetByID(ctx context.Context, id string) (*meeting.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*meeting.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMeetingRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMeetingRepository)(nil).GetByID), ctx, id)
}

// RemoveAgendaItemSpeaker mocks base method.
func (m *MockMeetingRepository) RemoveAgendaItemSpeaker(ctx context.Context, meetingID string, itemID, speakerID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAgendaItemSpeaker", ctx, meetingID, itemID, speakerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAgendaItemSpeaker indicates an expected call of RemoveAgendaItemSpeaker.
func (mr *MockMeetingRepositoryMockRecorder) RemoveAgendaItemSpeaker(ctx, meetingID, itemID, speakerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAgendaItemSpeaker", reflect.TypeOf((*MockMeetingRepository)(nil).RemoveAgendaItemSpeaker), ctx, meetingID, itemID, speakerID)
}

// RemovePerson mocks base method.
func (m *MockMeetingRepository) RemovePerson(ctx context.Context, meetingID string, personID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePerson", ctx, meetingID, personID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePerson indicates an expected call of RemovePerson.
func (mr *MockMeetingRepositoryMockRecorder) RemovePerson(ctx, meetingID, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePerson", reflect.TypeOf((*MockMeetingRepository)(nil).RemovePerson), ctx, meetingID, personID)
}

// ReorderAgendaItemSpeakers mocks base method.
func (m *MockMeetingRepository) ReorderAgendaItemSpeakers(ctx context.Context, meetingID string, itemID int, speakerIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderAgendaItemSpeakers", ctx, meetingID, itemID, speakerIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderAgendaItemSpeakers indicates an expected call of ReorderAgendaItemSpeakers.
func (mr *MockMeetingRepositoryMockRecorder) ReorderAgendaItemSpeakers(ctx, meetingID, itemID, speakerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderAgendaItemSpeakers", reflect.TypeOf((*MockMeetingRepository)(nil).ReorderAgendaItemSpeakers), ctx, meetingID, itemID, speakerIDs)
}

// ReorderAgendaItems mocks base method.
func (m *MockMeetingRepository) ReorderAgendaItems(ctx context.Context, meetingID string, agendaItemIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderAgendaItems", ctx, meetingID, agendaItemIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderAgendaItems indicates an expected call of ReorderAgendaItems.
func (mr *MockMeetingRepositoryMockRecorder) ReorderAgendaItems(ctx, meetingID, agendaItemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderAgendaItems", reflect.TypeOf((*MockMeetingRepository)(nil).ReorderAgendaItems), ctx, meetingID, agendaItemIDs)
}

// ReorderPeople mocks base method.
func (m *MockMeetingRepository) ReorderPeople(ctx context.Context, meetingID string, personIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderPeople", ctx, meetingID, personIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderPeople indicates an expected call of ReorderPeople.
func (mr *MockMeetingRepositoryMockRecorder) ReorderPeople(ctx, meetingID, personIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderPeople", reflect.TypeOf((*MockMeetingRepository)(nil).ReorderPeople), ctx, meetingID, personIDs)
}

// SetChairperson mocks base method.
func (m *MockMeetingRepository) SetChairperson(ctx context.Context, meetingID string, personID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChairperson", ctx, meetingID, personID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetChairperson indicates an expected call of SetChairperson.
func (mr *MockMeetingRepositoryMockRecorder) SetChairperson(ctx, meetingID, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChairperson", reflect.TypeOf((*MockMeetingRepository)(nil).SetChairperson), ctx, meetingID, personID)
}

// Update mocks base method.
func (m *MockMeetingRepository) Update(ctx context.Context, id, title string, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, title, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMeetingRepositoryMockRecorder) Update(ctx, id, title, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMeetingRepository)(nil).Update), ctx, id, title, date)
}

// UpdateAgendaItem mocks base method.
func (m *MockMeetingRepository) UpdateAgendaItem(ctx context.Context, meetingID string, itemID int, text string, speakerIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgendaItem", ctx, meetingID, itemID, text, speakerIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAgendaItem indicates an expected call of UpdateAgendaItem.
func (mr *MockMeetingRepositoryMockRecorder) UpdateAgendaItem(ctx, meetingID, itemID, text, speakerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgendaItem", reflect.TypeOf((*MockMeetingRepository)(nil).UpdateAgendaItem), ctx, meetingID, itemID, text, speakerIDs)
}
